#!/usr/bin/env bash
# spec-lint.sh — the project's spec-traceability linter (generated by scaffold-generate; placeholder-only).
#
# ONE shared anchor model, three subcommands:
#
#   scripts/spec-lint.sh brief <docs/briefs/NNN-....md>   orchestrator runs PRE-DISPATCH (mandatory);
#                                                         /tdd Step 0 re-runs only on a stamp mismatch
#   scripts/spec-lint.sh tests <phase-id>                 phase-exit row: every phase anchor has a
#                                                         spec(§X)-tagged test or a named waiver
#   scripts/spec-lint.sh reqs                             WARN-ONLY REQ→phase coverage (derived, W2-1)
#
# Anchors are `§X[.Y]` tokens and `#named-anchor` tokens. Lines mentioning LESSONS are excluded from
# anchor extraction (lesson refs are not spec anchors). Prefix-aware containment: §4.3 ⊂ §4.
# In multi-track mode the `tests` subcommand is inherently track-scoped — it audits ONE phase, and a
# phase belongs to one track.
#
# Exit: brief/tests exit non-zero on a failed check; reqs always exits 0 (warn-only).

set -euo pipefail

ARCH_DOC="ARCHITECTURE.md"
TRACKER="IMPLEMENTATION_PLAN.md"

FAIL=0
ok()   { printf '  PASS %s\n' "$*"; }
bad()  { printf '  FAIL %s\n' "$*"; FAIL=1; }
note() { printf '  note %s\n' "$*"; }

# ---- shared anchor extraction --------------------------------------------------------------------
# stdin → one anchor per line (§-form and #-form), LESSONS lines excluded, deduped.
extract_anchors() {
  grep -v 'LESSONS' \
    | grep -oE '§[0-9]+(\.[0-9]+)*|#[a-z][a-z0-9-]{2,}' \
    | sort -u || true
}

# anchor exists in the arch doc: §-form must match a real `## §` heading prefix (NOT the Spec Anchor
# Index); #-form must match an explicit id="..."/heading anchor.
anchor_in_arch() { # $1 = anchor
  case "$1" in
    '§'*)
      local n="${1#§}"
      grep -E "^##+ *§${n%%.*}([^0-9]|$)" "$ARCH_DOC" >/dev/null 2>&1 ;;
    '#'*)
      local id="${1#\#}"
      grep -E "id=\"${id}\"|^##+ .*\{#${id}\}" "$ARCH_DOC" >/dev/null 2>&1 ;;
  esac
}

# prefix containment: is $1 within the set on stdin (one per line)? §4.3 is contained by §4.
contained_in_set() { # $1 = anchor; stdin = set
  local a="$1" s
  while IFS= read -r s; do
    [ -z "$s" ] && continue
    [ "$a" = "$s" ] && return 0
    case "$a" in "$s".*) return 0 ;; esac     # §4.3 ⊂ §4
  done
  return 1
}

# the phase's `**Spec anchors:**` line (raw), given a phase id
phase_anchor_line() { # $1 = phase id
  awk -v p="$1" '
    $0 ~ "^## Phase[[:space:]]+" p "([^0-9A-Za-z]|$)" {inphase=1; next}
    inphase && /^## / {exit}
    inphase && /\*\*Spec anchors:\*\*/ {print; exit}
  ' "$TRACKER"
}

# the `## WAVE work` section's `**Spec anchors:**` line — the goal-driven WAVE tasks (W1-*/W2-*/…)
# share one anchor set rather than each carrying a `## Phase N` Spec-anchors line.
wave_anchor_line() {
  awk '
    /^## WAVE work/ {inwave=1; next}
    inwave && /^## / {exit}
    inwave && /\*\*Spec anchors:\*\*/ {print; exit}
  ' "$TRACKER"
}

# ---- brief <path> --------------------------------------------------------------------------------
cmd_brief() {
  local brief="${1:?usage: spec-lint.sh brief <path>}"
  [ -f "$brief" ] || { echo "spec-lint: no such brief: $brief"; exit 1; }

  # 1. every cited anchor exists in the arch doc
  local anchors a
  anchors=$(extract_anchors < "$brief")
  for a in $anchors; do
    anchor_in_arch "$a" || bad "anchor $a cited in the brief has no matching heading/id in $ARCH_DOC"
  done

  # 2. Task ID(s) exist in the tracker with unticked work (bundles cite several). Two ID schemes:
  #    numeric phase tasks (P2.1 → `### 2.1` heading) and WAVE goal tasks (W1-prof → a
  #    `- [ ] **W1-prof**` checkbox bullet under a `### WAVE-N` heading). A brief uses one scheme.
  local task_line task_ids wave_ids tid
  task_line=$(grep -E '^\- \*\*Task ID:?\*\*' "$brief" || true)
  task_ids=$(printf '%s\n' "$task_line" | grep -oE '[A-Za-z]+[0-9]*\.[0-9]+' | sort -u || true)
  wave_ids=$(printf '%s\n' "$task_line" | grep -oE 'W[0-9]+-[A-Za-z0-9]+' | sort -u || true)
  [ -n "$task_ids" ] || [ -n "$wave_ids" ] || bad "no Task ID line found (## Use case + traceability)"
  for tid in $task_ids; do
    # Tracker task headings are numeric (### 2.1); brief Task IDs are alpha-prefixed (P2.1) per the
    # brief-template convention. Strip the leading non-digit prefix to match (P2.1 → 2.1). The
    # extraction also drops a trailing sub-letter (P2.1a → P2.1 → 2.1), so a 2.1a/2.1b sub-slice
    # resolves to its parent task's heading + checkbox.
    local tnum="${tid#"${tid%%[0-9]*}"}"
    if ! grep -E "^###+ *${tnum}([^0-9]|$)" "$TRACKER" >/dev/null 2>&1; then
      bad "task $tid (→ ${tnum}) not found in $TRACKER"
    elif ! awk -v t="$tnum" '
        $0 ~ "^###+ *" t "([^0-9]|$)" {intask=1; next}
        intask && /^###? / {exit}
        intask && /^- \[ \]/ {found=1}
        END {exit !found}' "$TRACKER"; then
      bad "task $tid has no unticked checkbox in $TRACKER (already done, or mis-cited)"
    fi
  done
  # WAVE goal tasks live as `- [ ] **W<n>-<id>**` checkbox bullets (not `###` headings).
  for tid in $wave_ids; do
    if grep -E "^- \[ \] \*\*${tid}\*\*" "$TRACKER" >/dev/null 2>&1; then
      : # present + unticked
    elif grep -E "^- \[[xX]\] \*\*${tid}\*\*" "$TRACKER" >/dev/null 2>&1; then
      bad "WAVE task $tid is already ticked in $TRACKER (mis-cited)"
    else
      bad "WAVE task $tid not found as an unticked checkbox in $TRACKER"
    fi
  done

  # 3. brief anchors ⊆ the phase's (or WAVE work's) Spec anchors (prefix-aware), unless explicitly widened
  local pline pset phaselabel
  if [ -n "$task_ids" ]; then
    local phase="${task_ids%%.*}"; phase="${phase%%$'\n'*}"
    local pnum="${phase#"${phase%%[0-9]*}"}"   # P2 → 2 (tracker phase headings are numeric: "## Phase 2")
    pline=$(phase_anchor_line "$pnum")
    phaselabel="phase $phase"
  else
    pline=$(wave_anchor_line)
    phaselabel="WAVE work"
  fi
  if [ -z "$pline" ]; then
    note "$phaselabel has no Spec anchors: line — subset check skipped"
  else
    pset=$(printf '%s\n' "$pline" | extract_anchors)
    if grep -qi 'widens phase scope because' "$brief"; then
      note "brief declares it widens phase scope — subset check waived"
    else
      for a in $anchors; do
        printf '%s\n' "$pset" | contained_in_set "$a" \
          || bad "brief anchor $a is outside $phaselabel's Spec anchors ($(printf '%s' "$pset" | tr '\n' ' ')) — add an explicit 'widens phase scope because…' line or fix the anchor"
      done
    fi
  fi

  # 4. Wiring / entry point section present (Step 7.5 target)
  if grep -qE '^## Wiring / entry point' "$brief"; then
    grep -A3 -E '^## Wiring / entry point' "$brief" | grep -qiE 'none — wiring lands in|[a-zA-Z]' \
      && : # present (either a real entry point or the explicit deferral form)
  else
    bad "missing '## Wiring / entry point (Step 7.5)' section (accept 'none — wiring lands in <slice-id>')"
  fi

  # 5. ADVISORY: acceptance bullets vs RED-outline entries (Step-2.5 coverage signal, not a gate)
  local acc red
  acc=$(awk '/^## Acceptance criteria/{f=1;next} /^## /{f=0} f && /^- \[ \]/' "$brief" | grep -vcE '/preflight|tests in|test in' || true)
  red=$(awk '/^## RED test outline/{f=1;next} /^## /{f=0} f && /^[0-9]+\./' "$brief" | wc -l | tr -d ' ')
  note "advisory: $acc behavior acceptance bullet(s) vs $red RED-outline test(s) — Step 2.5 maps each bullet to a test or a not-tested-because note"

  # 6. WARN-ONLY: REQ-IDs line presence (REQ coverage is derived; an explicit line is the rare override)
  grep -qE 'Implements: *REQ-' "$brief" || note "warn: no explicit REQ line (fine — REQ coverage derives from the cited §s)"

  if [ "$FAIL" -ne 0 ]; then echo "spec-lint brief FAIL $brief"; exit 1; fi
  printf 'spec-lint brief PASS %s @%s\n' "$brief" "$(shasum "$brief" | cut -c1-8)"
}

# ---- tests <phase> -------------------------------------------------------------------------------
cmd_tests() {
  local phase="${1:?usage: spec-lint.sh tests <phase-id>}"
  local pline
  pline=$(phase_anchor_line "$phase")
  [ -n "$pline" ] || { echo "spec-lint: phase $phase has no Spec anchors: line in $TRACKER"; exit 1; }

  # tag search across the test tree (any file with 'test' in its path, outside docs/)
  tag_hits() { # $1 = anchor (§-form or #-form)
    grep -rl --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=docs --exclude-dir=scripts \
      --exclude-dir=target --exclude-dir=.codegraph \
      -e "spec($1" . 2>/dev/null | grep -i 'test' || true
  }

  local a hits waived
  for a in $(printf '%s\n' "$pline" | extract_anchors); do
    # named waiver classes, read off the Spec anchors line itself:
    #   §X (non-TDD: <how it's covered instead>)  ·  §X (covered-by: <evidence>)  ·  §X (benchmark)
    waived=$(printf '%s\n' "$pline" | grep -oE "$(printf '%s' "$a" | sed 's/[.[\*^$]/\\&/g')\`? *\((non-TDD|covered-by|benchmark)[^)]*\)" || true)
    if [ -n "$waived" ]; then ok "$a waived: $waived"; continue; fi
    # prefix-aware: a tag spec(§4.3) covers the phase anchor §4
    hits=$(tag_hits "$a")
    if [ -n "$hits" ]; then
      ok "$a covered: $(printf '%s\n' "$hits" | head -1)$([ "$(printf '%s\n' "$hits" | wc -l | tr -d ' ')" -gt 1 ] && printf ' (+%s more)' "$(($(printf '%s\n' "$hits" | wc -l | tr -d ' ')-1))")"
    else
      bad "$a has no test carrying a spec(${a}...) tag and no waiver on the phase's Spec anchors line"
    fi
  done

  # ADVISORY: out-of-set tags (a Step-9 item — anchor missing from the plan, or a stale tag); never a failure
  local all_tracker_anchors stray t
  all_tracker_anchors=$(grep '\*\*Spec anchors:\*\*' "$TRACKER" | extract_anchors)
  stray=$(grep -rho --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=docs --exclude-dir=scripts \
            --exclude-dir=target --exclude-dir=.codegraph \
            -e 'spec(§[0-9][0-9.]*' -e 'spec(#[a-z][a-z0-9-]*' . 2>/dev/null | sed 's/^spec(//' | sort -u || true)
  for t in $stray; do
    printf '%s\n' "$all_tracker_anchors" | contained_in_set "$t" \
      || note "advisory: test tag spec($t) maps to no phase's Spec anchors line — flag at Step 9 (missing plan anchor, or stale tag)"
  done

  if [ "$FAIL" -ne 0 ]; then echo "spec-lint tests FAIL (phase $phase)"; exit 1; fi
  echo "spec-lint tests PASS (phase $phase)"
}

# ---- reqs (WARN-ONLY) ----------------------------------------------------------------------------
cmd_reqs() {
  # head: the persisted PRD→REQ coverage table when present (arch-finalize dimension 1)
  [ -f docs/gap-audits/prd-req-coverage.md ] \
    && note "PRD→REQ head present: docs/gap-audits/prd-req-coverage.md" \
    || note "no PRD→REQ coverage table (docs/gap-audits/prd-req-coverage.md) — head check skipped"

  # Spec Anchor Index → REQ → § map
  if ! grep -qE '^## Spec Anchor Index' "$ARCH_DOC"; then
    echo "spec-lint reqs: no Spec Anchor Index in $ARCH_DOC — re-run /arch-finalize to add it (warn-only)"; exit 0
  fi
  local rows; rows=$(awk '/^## Spec Anchor Index/{f=1;next} /^## /{f=0} f && /^\| *REQ-/' "$ARCH_DOC")
  if [ -z "$rows" ]; then
    echo "spec-lint reqs: Spec Anchor Index has no REQ rows — nothing to check (warn-only)"; exit 0
  fi

  local all_phase_anchors covered=0 total=0 req secs s line
  all_phase_anchors=$(grep '\*\*Spec anchors:\*\*' "$TRACKER" | extract_anchors)
  while IFS= read -r line; do
    req=$(printf '%s' "$line" | awk -F'|' '{gsub(/ /,"",$2); print $2}')
    secs=$(printf '%s\n' "$line" | extract_anchors)
    total=$((total+1))
    local hit=false
    for s in $secs; do
      if printf '%s\n' "$all_phase_anchors" | contained_in_set "$s"; then hit=true; break; fi
      # also covered when a phase cites a SUB-anchor of the REQ's § (phase §4.3 covers REQ §4)
      while IFS= read -r pa; do case "$pa" in "$s".*) hit=true; break ;; esac; done <<< "$all_phase_anchors"
      [ "$hit" = true ] && break
    done
    if [ "$hit" = true ]; then covered=$((covered+1)); else
      note "warn: $req (→ $(printf '%s' "$secs" | tr '\n' ' ')) is on no phase's Spec anchors line"
    fi
  done <<< "$rows"
  echo "spec-lint reqs: $covered/$total REQ rows covered by phase anchors (warn-only)"
}

case "${1:-}" in
  brief) shift; cmd_brief "$@" ;;
  tests) shift; cmd_tests "$@" ;;
  reqs)  shift; cmd_reqs ;;
  *) echo "usage: spec-lint.sh brief <path> | tests <phase-id> | reqs"; exit 2 ;;
esac
